basePath: /
definitions:
  entities.Address:
    properties:
      city:
        type: string
      complement:
        type: string
      country:
        type: string
      location:
        $ref: '#/definitions/entities.Location'
      neighborhood:
        type: string
      number:
        type: string
      state:
        type: string
      street:
        type: string
      zip_code:
        type: string
    type: object
  entities.Breed:
    properties:
      active:
        type: boolean
      created_at:
        type: string
      deactivated_at:
        type: string
      id:
        type: string
      name:
        type: string
      specie_id:
        type: string
      updated_at:
        type: string
    type: object
  entities.Location:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    type: object
  entities.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entities.Pet:
    properties:
      active:
        type: boolean
      age:
        type: integer
      breed:
        $ref: '#/definitions/entities.Breed'
      created_at:
        type: string
      deactivated_at:
        type: string
      id:
        type: string
      name:
        type: string
      notes:
        type: string
      photos:
        items:
          $ref: '#/definitions/entities.Photo'
        type: array
      specie:
        $ref: '#/definitions/entities.Specie'
      updated_at:
        type: string
      user_id:
        type: string
      weight:
        type: number
    type: object
  entities.Phone:
    properties:
      area_code:
        type: string
      country_code:
        type: string
      number:
        type: string
    type: object
  entities.Photo:
    properties:
      active:
        type: boolean
      created_at:
        type: string
      deactivated_at:
        type: string
      id:
        type: string
      updated_at:
        type: string
      url:
        type: string
    type: object
  entities.Specie:
    properties:
      active:
        type: boolean
      created_at:
        type: string
      deactivated_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  entities.User:
    properties:
      active:
        type: boolean
      address:
        $ref: '#/definitions/entities.Address'
      created_at:
        type: string
      deactivated_at:
        type: string
      email_verified:
        type: boolean
      id:
        type: string
      login:
        $ref: '#/definitions/entities.Login'
      name:
        type: string
      pets:
        items:
          $ref: '#/definitions/entities.Pet'
        type: array
      phone:
        $ref: '#/definitions/entities.Phone'
      photos:
        items:
          $ref: '#/definitions/entities.Photo'
        type: array
      updated_at:
        type: string
      user_type:
        type: string
    type: object
  exceptions.ProblemDetails:
    properties:
      detail:
        type: string
      instance:
        type: string
      status:
        type: integer
      title:
        type: string
      type:
        type: string
    type: object
  usecases.ChangePasswordInput:
    properties:
      current_password:
        type: string
      new_password:
        type: string
      user_id:
        type: string
    type: object
  usecases.ChangePasswordOutput:
    properties:
      detail:
        type: string
      message:
        type: string
    type: object
  usecases.CheckEmailExistsInput:
    properties:
      email:
        type: string
    type: object
  usecases.CheckEmailExistsOutput:
    properties:
      exists:
        type: boolean
      message:
        type: string
    type: object
  usecases.CheckPhoneExistsInput:
    properties:
      area_code:
        type: string
      country_code:
        type: string
      number:
        type: string
    type: object
  usecases.CheckPhoneExistsOutput:
    properties:
      exists:
        type: boolean
      message:
        type: string
    type: object
  usecases.DeactivateUserInput:
    properties:
      user_id:
        type: string
    type: object
  usecases.DeactivateUserOutput:
    properties:
      detail:
        type: string
      message:
        type: string
    type: object
  usecases.DeleteUserInput:
    properties:
      user_id:
        type: string
    type: object
  usecases.DeleteUserOutput:
    properties:
      detail:
        type: string
      message:
        type: string
    type: object
  usecases.GetProfileOutput:
    properties:
      user:
        $ref: '#/definitions/entities.User'
    type: object
  usecases.GetUserByIDOutput:
    properties:
      user:
        $ref: '#/definitions/entities.User'
    type: object
  usecases.ListUsersOutput:
    properties:
      pagination:
        $ref: '#/definitions/usecases.PaginationMetadata'
      users:
        items:
          $ref: '#/definitions/entities.User'
        type: array
    type: object
  usecases.PaginationMetadata:
    properties:
      current_page:
        type: integer
      per_page:
        type: integer
      total_pages:
        type: integer
      total_records:
        type: integer
    type: object
  usecases.ReactivateUserInput:
    properties:
      user_id:
        type: string
    type: object
  usecases.ReactivateUserOutput:
    properties:
      detail:
        type: string
      message:
        type: string
    type: object
  usecases.RegisterUserInput:
    properties:
      address:
        $ref: '#/definitions/entities.Address'
      login:
        $ref: '#/definitions/entities.Login'
      name:
        type: string
      phone:
        $ref: '#/definitions/entities.Phone'
      user_type:
        type: string
    type: object
  usecases.RegisterUserOutput:
    properties:
      detail:
        type: string
      message:
        type: string
    type: object
  usecases.UpdateEmailVerifiedInput:
    properties:
      user_id:
        type: string
      verified:
        type: boolean
    type: object
  usecases.UpdateEmailVerifiedOutput:
    properties:
      detail:
        type: string
      message:
        type: string
    type: object
  usecases.UpdateUserInput:
    properties:
      address:
        $ref: '#/definitions/entities.Address'
      name:
        type: string
      phone:
        $ref: '#/definitions/entities.Phone'
      user_id:
        type: string
      user_type:
        type: string
    type: object
  usecases.UpdateUserOutput:
    properties:
      detail:
        type: string
      message:
        type: string
      user:
        $ref: '#/definitions/entities.User'
    type: object
host: localhost:8080
info:
  contact:
    email: guilherme@example.com
    name: Guilherme Amorim
  description: API para gerenciamento de serviços pet.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Pet Services API
  version: "1.0"
paths:
  /users:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID do usuário
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.DeleteUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.DeleteUserOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Deleta usuário
      tags:
      - users
    get:
      parameters:
      - description: Página
        in: query
        name: page
        type: integer
      - description: Limite
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecases.ListUsersOutput'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Lista usuários
      tags:
      - users
    put:
      consumes:
      - application/json
      parameters:
      - description: Dados do usuário
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.UpdateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.UpdateUserOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Atualiza dados do usuário
      tags:
      - users
  /users/{user_id}:
    get:
      parameters:
      - description: ID do usuário
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.GetUserByIDOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Busca usuário por ID
      tags:
      - users
  /users/change-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados de senha
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.ChangePasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.ChangePasswordOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Altera senha do usuário
      tags:
      - users
  /users/check-email:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.CheckEmailExistsInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.CheckEmailExistsOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Verifica se email existe
      tags:
      - users
  /users/check-phone:
    post:
      consumes:
      - application/json
      parameters:
      - description: Telefone
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.CheckPhoneExistsInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.CheckPhoneExistsOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Verifica se telefone existe
      tags:
      - users
  /users/deactivate:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID do usuário
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.DeactivateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.DeactivateUserOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Desativa usuário
      tags:
      - users
  /users/profile:
    get:
      parameters:
      - description: ID do usuário
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.GetProfileOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Retorna o perfil do usuário
      tags:
      - users
  /users/reactivate:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID do usuário
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.ReactivateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.ReactivateUserOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Reativa usuário
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados do usuário
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.RegisterUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/usecases.RegisterUserOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Registra um novo usuário
      tags:
      - users
  /users/update-email-verified:
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados de verificação
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.UpdateEmailVerifiedInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.UpdateEmailVerifiedOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exceptions.ProblemDetails'
      summary: Atualiza verificação de email
      tags:
      - users
swagger: "2.0"
