export type { AuthGateway } from "./auth-gateway";
export type { UserGateway } from "./user-gateway";
export type { ReferenceGateway } from "./reference-gateway";
export type { PetGateway } from "./pet-gateway";
export type { SpecieGateway } from "./specie-gateway";
export type { ProviderGateway } from "./provider-gateway";
export type { ServiceGateway } from "./service-gateway";
export type { RequestGateway } from "./request-gateway";
export type { ReviewGateway } from "./review-gateway";
