package reference

var Countries = []Country{
	{Name: "Afeganistão", DialCode: "+93", Code: "AF", Flag: "🇦🇫"},
	{Name: "Albânia", DialCode: "+355", Code: "AL", Flag: "🇦🇱"},
	{Name: "Argélia", DialCode: "+213", Code: "DZ", Flag: "🇩🇿"},
	{Name: "Samoa Americana", DialCode: "+1684", Code: "AS", Flag: "🇦🇸"},
	{Name: "Andorra", DialCode: "+376", Code: "AD", Flag: "🇦🇩"},
	{Name: "Angola", DialCode: "+244", Code: "AO", Flag: "🇦🇴"},
	{Name: "Anguilla", DialCode: "+1264", Code: "AI", Flag: "🇦🇮"},
	{Name: "Antártida", DialCode: "+672", Code: "AQ", Flag: "🇦🇶"},
	{Name: "Antígua e Barbuda", DialCode: "+1268", Code: "AG", Flag: "🇦🇬"},
	{Name: "Argentina", DialCode: "+54", Code: "AR", Flag: "🇦🇷"},
	{Name: "Armênia", DialCode: "+374", Code: "AM", Flag: "🇦🇲"},
	{Name: "Aruba", DialCode: "+297", Code: "AW", Flag: "🇦🇼"},
	{Name: "Austrália", DialCode: "+61", Code: "AU", Flag: "🇦🇺"},
	{Name: "Áustria", DialCode: "+43", Code: "AT", Flag: "🇦🇹"},
	{Name: "Azerbaijão", DialCode: "+994", Code: "AZ", Flag: "🇦🇿"},
	{Name: "Bahamas", DialCode: "+1242", Code: "BS", Flag: "🇧🇸"},
	{Name: "Bahrein", DialCode: "+973", Code: "BH", Flag: "🇧🇭"},
	{Name: "Bangladesh", DialCode: "+880", Code: "BD", Flag: "🇧🇩"},
	{Name: "Barbados", DialCode: "+1246", Code: "BB", Flag: "🇧🇧"},
	{Name: "Belarus", DialCode: "+375", Code: "BY", Flag: "🇧🇾"},
	{Name: "Bélgica", DialCode: "+32", Code: "BE", Flag: "🇧🇪"},
	{Name: "Belize", DialCode: "+501", Code: "BZ", Flag: "🇧🇿"},
	{Name: "Benin", DialCode: "+229", Code: "BJ", Flag: "🇧🇯"},
	{Name: "Bermudas", DialCode: "+1441", Code: "BM", Flag: "🇧🇲"},
	{Name: "Butão", DialCode: "+975", Code: "BT", Flag: "🇧🇹"},
	{Name: "Bolívia", DialCode: "+591", Code: "BO", Flag: "🇧🇴"},
	{Name: "Bósnia-Herzegóvina", DialCode: "+387", Code: "BA", Flag: "🇧🇦"},
	{Name: "Botsuana", DialCode: "+267", Code: "BW", Flag: "🇧🇼"},
	{Name: "Brasil", DialCode: "+55", Code: "BR", Flag: "🇧🇷"},
	{Name: "Brasil", DialCode: "+55", Code: "BR", Flag: "🇧🇷"},
	{Name: "Território Britânico do Oceano índico", DialCode: "+246", Code: "IO", Flag: "🇮🇴"},
	{Name: "Brunei", DialCode: "+673", Code: "BN", Flag: "🇧🇳"},
	{Name: "Bulgária", DialCode: "+359", Code: "BG", Flag: "🇧🇬"},
	{Name: "Burkina Fasso", DialCode: "+226", Code: "BF", Flag: "🇧🇫"},
	{Name: "Burundi", DialCode: "+257", Code: "BI", Flag: "🇧🇮"},
	{Name: "Camboja", DialCode: "+855", Code: "KH", Flag: "🇰🇭"},
	{Name: "Camarões", DialCode: "+237", Code: "CM", Flag: "🇨🇲"},
	{Name: "Canadá", DialCode: "+1", Code: "CA", Flag: "🇨🇦"},
	{Name: "Cabo Verde", DialCode: "+238", Code: "CV", Flag: "🇨🇻"},
	{Name: "Ilhas Cayman", DialCode: "+345", Code: "KY", Flag: "🇰🇾"},
	{Name: "República Centro-Africana", DialCode: "+236", Code: "CF", Flag: "🇨🇫"},
	{Name: "Chade", DialCode: "+235", Code: "TD", Flag: "🇹🇩"},
	{Name: "Chile", DialCode: "+56", Code: "CL", Flag: "🇨🇱"},
	{Name: "China", DialCode: "+86", Code: "CN", Flag: "🇨🇳"},
	{Name: "Ilha Natal", DialCode: "+61", Code: "CX", Flag: "🇨🇽"},
	{Name: "Ilhas Cocos", DialCode: "+61", Code: "CC", Flag: "🇨🇨"},
	{Name: "Colômbia", DialCode: "+57", Code: "CO", Flag: "🇨🇴"},
	{Name: "Comores", DialCode: "+269", Code: "KM", Flag: "🇰🇲"},
	{Name: "Congo", DialCode: "+242", Code: "CG", Flag: "🇨🇬"},
	{Name: "República Democrática do Congo", DialCode: "+243", Code: "CD", Flag: "🇨🇩"},
	{Name: "Ilhas Cook", DialCode: "+682", Code: "CK", Flag: "🇨🇰"},
	{Name: "Costa Rica", DialCode: "+506", Code: "CR", Flag: "🇨🇷"},
	{Name: "Costa do Marfim", DialCode: "+225", Code: "CI", Flag: "🇨🇮"},
	{Name: "Croácia", DialCode: "+385", Code: "HR", Flag: "🇭🇷"},
	{Name: "Cuba", DialCode: "+53", Code: "CU", Flag: "🇨🇺"},
	{Name: "Chipre", DialCode: "+357", Code: "CY", Flag: "🇨🇾"},
	{Name: "República Tcheca", DialCode: "+420", Code: "CZ", Flag: "🇨🇿"},
	{Name: "Dinamarca", DialCode: "+45", Code: "DK", Flag: "🇩🇰"},
	{Name: "Djibuti", DialCode: "+253", Code: "DJ", Flag: "🇩🇯"},
	{Name: "Dominica", DialCode: "+1767", Code: "DM", Flag: "🇩🇲"},
	{Name: "República Dominicana", DialCode: "+1849", Code: "DO", Flag: "🇩🇴"},
	{Name: "Equador", DialCode: "+593", Code: "EC", Flag: "🇪🇨"},
	{Name: "Egito", DialCode: "+20", Code: "EG", Flag: "🇪🇬"},
	{Name: "El Salvador", DialCode: "+503", Code: "SV", Flag: "🇸🇻"},
	{Name: "Guiné Equatorial", DialCode: "+240", Code: "GQ", Flag: "🇬🇶"},
	{Name: "Eritréia", DialCode: "+291", Code: "ER", Flag: "🇪🇷"},
	{Name: "Estônia", DialCode: "+372", Code: "EE", Flag: "🇪🇪"},
	{Name: "Etiópia", DialCode: "+251", Code: "ET", Flag: "🇪🇹"},
	{Name: "Ilhas Malvinas", DialCode: "+500", Code: "FK", Flag: "🇫🇰"},
	{Name: "Ilhas Faroes", DialCode: "+298", Code: "FO", Flag: "🇫🇴"},
	{Name: "Fiji", DialCode: "+679", Code: "FJ", Flag: "🇫🇯"},
	{Name: "Finlândia", DialCode: "+358", Code: "FI", Flag: "🇫🇮"},
	{Name: "França", DialCode: "+33", Code: "FR", Flag: "🇫🇷"},
	{Name: "Guiana Francesa", DialCode: "+594", Code: "GF", Flag: "🇬🇫"},
	{Name: "Polinésia Francesa", DialCode: "+689", Code: "PF", Flag: "🇵🇫"},
	{Name: "Gabão", DialCode: "+241", Code: "GA", Flag: "🇬🇦"},
	{Name: "Gâmbia", DialCode: "+220", Code: "GM", Flag: "🇬🇲"},
	{Name: "Geórgia", DialCode: "+995", Code: "GE", Flag: "🇬🇪"},
	{Name: "Alemanha", DialCode: "+49", Code: "DE", Flag: "🇩🇪"},
	{Name: "Gana", DialCode: "+233", Code: "GH", Flag: "🇬🇭"},
	{Name: "Gibraltar", DialCode: "+350", Code: "GI", Flag: "🇬🇮"},
	{Name: "Grécia", DialCode: "+30", Code: "GR", Flag: "🇬🇷"},
	{Name: "Groelândia", DialCode: "+299", Code: "GL", Flag: "🇬🇱"},
	{Name: "Granada", DialCode: "+1473", Code: "GD", Flag: "🇬🇩"},
	{Name: "Guadalupe", DialCode: "+590", Code: "GP", Flag: "🇬🇵"},
	{Name: "Guam (Território dos Estados Unidos)", DialCode: "+1671", Code: "GU", Flag: "🇬🇺"},
	{Name: "Guatemala", DialCode: "+502", Code: "GT", Flag: "🇬🇹"},
	{Name: "Guernsey", DialCode: "+44", Code: "GG", Flag: "🇬🇬"},
	{Name: "Guiné", DialCode: "+224", Code: "GN", Flag: "🇬🇳"},
	{Name: "Guiné-Bissau", DialCode: "+245", Code: "GW", Flag: "🇬🇼"},
	{Name: "Guiana", DialCode: "+592", Code: "GY", Flag: "🇬🇾"},
	{Name: "Haiti", DialCode: "+509", Code: "HT", Flag: "🇭🇹"},
	{Name: "Vaticano", DialCode: "+379", Code: "VA", Flag: "🇻🇦"},
	{Name: "Honduras", DialCode: "+504", Code: "HN", Flag: "🇭🇳"},
	{Name: "Hong Kong", DialCode: "+852", Code: "HK", Flag: "🇭🇰"},
	{Name: "Hungria", DialCode: "+36", Code: "HU", Flag: "🇭🇺"},
	{Name: "Islândia", DialCode: "+354", Code: "IS", Flag: "🇮🇸"},
	{Name: "Índia", DialCode: "+91", Code: "IN", Flag: "🇮🇳"},
	{Name: "Indonésia", DialCode: "+62", Code: "ID", Flag: "🇮🇩"},
	{Name: "Irã", DialCode: "+98", Code: "IR", Flag: "🇮🇷"},
	{Name: "Iraque", DialCode: "+964", Code: "IQ", Flag: "🇮🇶"},
	{Name: "Irlanda", DialCode: "+353", Code: "IE", Flag: "🇮🇪"},
	{Name: "Ilha de Man", DialCode: "+44", Code: "IM", Flag: "🇮🇲"},
	{Name: "Israel", DialCode: "+972", Code: "IL", Flag: "🇮🇱"},
	{Name: "Itália", DialCode: "+39", Code: "IT", Flag: "🇮🇹"},
	{Name: "Jamaica", DialCode: "+1876", Code: "JM", Flag: "🇯🇲"},
	{Name: "Japão", DialCode: "+81", Code: "JP", Flag: "🇯🇵"},
	{Name: "Jersey", DialCode: "+44", Code: "JE", Flag: "🇯🇪"},
	{Name: "Jordânia", DialCode: "+962", Code: "JO", Flag: "🇯🇴"},
	{Name: "Cazaquistão", DialCode: "+77", Code: "KZ", Flag: "🇰🇿"},
	{Name: "Quênia", DialCode: "+254", Code: "KE", Flag: "🇰🇪"},
	{Name: "Kiribati", DialCode: "+686", Code: "KI", Flag: "🇰🇮"},
	{Name: "Coréia do Norte", DialCode: "+850", Code: "KP", Flag: "🇰🇵"},
	{Name: "Coréia do Sul", DialCode: "+82", Code: "KR", Flag: "🇰🇷"},
	{Name: "Kuait", DialCode: "+965", Code: "KW", Flag: "🇰🇼"},
	{Name: "Quirguistão", DialCode: "+996", Code: "KG", Flag: "🇰🇬"},
	{Name: "Laos", DialCode: "+856", Code: "LA", Flag: "🇱🇦"},
	{Name: "Letônia", DialCode: "+371", Code: "LV", Flag: "🇱🇻"},
	{Name: "Líbano", DialCode: "+961", Code: "LB", Flag: "🇱🇧"},
	{Name: "Lesoto", DialCode: "+266", Code: "LS", Flag: "🇱🇸"},
	{Name: "Libéria", DialCode: "+231", Code: "LR", Flag: "🇱🇷"},
	{Name: "Líbia", DialCode: "+218", Code: "LY", Flag: "🇱🇾"},
	{Name: "Liechtenstein", DialCode: "+423", Code: "LI", Flag: "🇱🇮"},
	{Name: "Lituânia", DialCode: "+370", Code: "LT", Flag: "🇱🇹"},
	{Name: "Luxemburgo", DialCode: "+352", Code: "LU", Flag: "🇱🇺"},
	{Name: "Macau", DialCode: "+853", Code: "MO", Flag: "🇲🇴"},
	{Name: "Macedônia (República Yugoslava)", DialCode: "+389", Code: "MK", Flag: "🇲🇰"},
	{Name: "Madagascar", DialCode: "+261", Code: "MG", Flag: "🇲🇬"},
	{Name: "Malaui", DialCode: "+265", Code: "MW", Flag: "🇲🇼"},
	{Name: "Malásia", DialCode: "+60", Code: "MY", Flag: "🇲🇾"},
	{Name: "Maldivas", DialCode: "+960", Code: "MV", Flag: "🇲🇻"},
	{Name: "Mali", DialCode: "+223", Code: "ML", Flag: "🇲🇱"},
	{Name: "Malta", DialCode: "+356", Code: "MT", Flag: "🇲🇹"},
	{Name: "Ilhas Marshall", DialCode: "+692", Code: "MH", Flag: "🇲🇭"},
	{Name: "Martinica", DialCode: "+596", Code: "MQ", Flag: "🇲🇶"},
	{Name: "Mauritânia", DialCode: "+222", Code: "MR", Flag: "🇲🇷"},
	{Name: "Maurício", DialCode: "+230", Code: "MU", Flag: "🇲🇺"},
	{Name: "Mayotte", DialCode: "+262", Code: "YT", Flag: "🇾🇹"},
	{Name: "México", DialCode: "+52", Code: "MX", Flag: "🇲🇽"},
	{Name: "Micronésia", DialCode: "+691", Code: "FM", Flag: "🇫🇲"},
	{Name: "Moldova", DialCode: "+373", Code: "MD", Flag: "🇲🇩"},
	{Name: "Mônaco", DialCode: "+377", Code: "MC", Flag: "🇲🇨"},
	{Name: "Mongólia", DialCode: "+976", Code: "MN", Flag: "🇲🇳"},
	{Name: "Montenegro", DialCode: "+382", Code: "ME", Flag: "🇲🇪"},
	{Name: "Montserrat", DialCode: "+1664", Code: "MS", Flag: "🇲🇸"},
	{Name: "Marrocos", DialCode: "+212", Code: "MA", Flag: "🇲🇦"},
	{Name: "Moçambique", DialCode: "+258", Code: "MZ", Flag: "🇲🇿"},
	{Name: "Myanma", DialCode: "+95", Code: "MM", Flag: "🇲🇲"},
	{Name: "Namíbia", DialCode: "+264", Code: "NA", Flag: "🇳🇦"},
	{Name: "Nauru", DialCode: "+674", Code: "NR", Flag: "🇳🇷"},
	{Name: "Nepal", DialCode: "+977", Code: "NP", Flag: "🇳🇵"},
	{Name: "Holanda", DialCode: "+31", Code: "NL", Flag: "🇳🇱"},
	{Name: "Netherlands Antilles", DialCode: "+599", Code: "AN", Flag: "🇦🇳"},
	{Name: "Nova Caledônia", DialCode: "+687", Code: "NC", Flag: "🇳🇨"},
	{Name: "Nova Zelândia", DialCode: "+64", Code: "NZ", Flag: "🇳🇿"},
	{Name: "Nicarágua", DialCode: "+505", Code: "NI", Flag: "🇳🇮"},
	{Name: "Níger", DialCode: "+227", Code: "NE", Flag: "🇳🇪"},
	{Name: "Nigéria", DialCode: "+234", Code: "NG", Flag: "🇳🇬"},
	{Name: "Niue", DialCode: "+683", Code: "NU", Flag: "🇳🇺"},
	{Name: "Ilhas Norfolk", DialCode: "+672", Code: "NF", Flag: "🇳🇫"},
	{Name: "Ilhas Marianas do Norte", DialCode: "+1670", Code: "MP", Flag: "🇲🇵"},
	{Name: "Noruega", DialCode: "+47", Code: "NO", Flag: "🇳🇴"},
	{Name: "Omã", DialCode: "+968", Code: "OM", Flag: "🇴🇲"},
	{Name: "Paquistão", DialCode: "+92", Code: "PK", Flag: "🇵🇰"},
	{Name: "Palau", DialCode: "+680", Code: "PW", Flag: "🇵🇼"},
	{Name: "Palestina", DialCode: "+970", Code: "PS", Flag: "🇵🇸"},
	{Name: "Panamá", DialCode: "+507", Code: "PA", Flag: "🇵🇦"},
	{Name: "Papua-Nova Guiné", DialCode: "+675", Code: "PG", Flag: "🇵🇬"},
	{Name: "Paraguai", DialCode: "+595", Code: "PY", Flag: "🇵🇾"},
	{Name: "Peru", DialCode: "+51", Code: "PE", Flag: "🇵🇪"},
	{Name: "Filipinas", DialCode: "+63", Code: "PH", Flag: "🇵🇭"},
	{Name: "Ilha Pitcairn", DialCode: "+872", Code: "PN", Flag: "🇵🇳"},
	{Name: "Polônia", DialCode: "+48", Code: "PL", Flag: "🇵🇱"},
	{Name: "Portugal", DialCode: "+351", Code: "PT", Flag: "🇵🇹"},
	{Name: "Porto Rico", DialCode: "+1939", Code: "PR", Flag: "🇵🇷"},
	{Name: "Qatar", DialCode: "+974", Code: "QA", Flag: "🇶🇦"},
	{Name: "Romênia", DialCode: "+40", Code: "RO", Flag: "🇷🇴"},
	{Name: "Rússia (antiga URSS) - Federação Russa", DialCode: "+7", Code: "RU", Flag: "🇷🇺"},
	{Name: "Ruanda", DialCode: "+250", Code: "RW", Flag: "🇷🇼"},
	{Name: "Ilha Reunião", DialCode: "+262", Code: "RE", Flag: "🇷🇪"},
	{Name: "São Bartolomeu", DialCode: "+590", Code: "BL", Flag: "🇧🇱"},
	{Name: "Santa Helena", DialCode: "+290", Code: "SH", Flag: "🇸🇭"},
	{Name: "São Cristóvão e Névis", DialCode: "+1869", Code: "KN", Flag: "🇰🇳"},
	{Name: "Santa Lúcia", DialCode: "+1758", Code: "LC", Flag: "🇱🇨"},
	{Name: "São Martim", DialCode: "+590", Code: "MF", Flag: "🇲🇫"},
	{Name: "Saint-Pierre e Miquelon", DialCode: "+508", Code: "PM", Flag: "🇵🇲"},
	{Name: "São Vicente e Granadinas", DialCode: "+1784", Code: "VC", Flag: "🇻🇨"},
	{Name: "Samoa Ocidental", DialCode: "+685", Code: "WS", Flag: "🇼🇸"},
	{Name: "San Marino", DialCode: "+378", Code: "SM", Flag: "🇸🇲"},
	{Name: "São Tomé e Príncipe", DialCode: "+239", Code: "ST", Flag: "🇸🇹"},
	{Name: "Arábia Saudita", DialCode: "+966", Code: "SA", Flag: "🇸🇦"},
	{Name: "Senegal", DialCode: "+221", Code: "SN", Flag: "🇸🇳"},
	{Name: "Sérvia", DialCode: "+381", Code: "RS", Flag: "🇷🇸"},
	{Name: "Ilhas Seychelles", DialCode: "+248", Code: "SC", Flag: "🇸🇨"},
	{Name: "Serra Leoa", DialCode: "+232", Code: "SL", Flag: "🇸🇱"},
	{Name: "Cingapura", DialCode: "+65", Code: "SG", Flag: "🇸🇬"},
	{Name: "Eslováquia", DialCode: "+421", Code: "SK", Flag: "🇸🇰"},
	{Name: "Eslovênia", DialCode: "+386", Code: "SI", Flag: "🇸🇮"},
	{Name: "Ilhas Salomão", DialCode: "+677", Code: "SB", Flag: "🇸🇧"},
	{Name: "Somália", DialCode: "+252", Code: "SO", Flag: "🇸🇴"},
	{Name: "África do Sul", DialCode: "+27", Code: "ZA", Flag: "🇿🇦"},
	{Name: "Ilhas Geórgia do Sul e Sandwich do Sul", DialCode: "+500", Code: "GS", Flag: "🇬🇸"},
	{Name: "Espanha", DialCode: "+34", Code: "ES", Flag: "🇪🇸"},
	{Name: "Sri Lanka", DialCode: "+94", Code: "LK", Flag: "🇱🇰"},
	{Name: "Sudão", DialCode: "+249", Code: "SD", Flag: "🇸🇩"},
	{Name: "Sudão do Sul", DialCode: "+211", Code: "SS", Flag: "🇸🇸"},
	{Name: "Suriname", DialCode: "+597", Code: "SR", Flag: "🇸🇷"},
	{Name: "Svalbard", DialCode: "+47", Code: "SJ", Flag: "🇸🇯"},
	{Name: "Suazilândia", DialCode: "+268", Code: "SZ", Flag: "🇸🇿"},
	{Name: "Suécia", DialCode: "+46", Code: "SE", Flag: "🇸🇪"},
	{Name: "Suíça", DialCode: "+41", Code: "CH", Flag: "🇨🇭"},
	{Name: "Síria", DialCode: "+963", Code: "SY", Flag: "🇸🇾"},
	{Name: "Taiwan", DialCode: "+886", Code: "TW", Flag: "🇹🇼"},
	{Name: "Tadjiquistão", DialCode: "+992", Code: "TJ", Flag: "🇹🇯"},
	{Name: "Tanzânia", DialCode: "+255", Code: "TZ", Flag: "🇹🇿"},
	{Name: "Tailândia", DialCode: "+66", Code: "TH", Flag: "🇹🇭"},
	{Name: "Timor-Leste", DialCode: "+670", Code: "TL", Flag: "🇹🇱"},
	{Name: "Togo", DialCode: "+228", Code: "TG", Flag: "🇹🇬"},
	{Name: "Ilhas Tokelau", DialCode: "+690", Code: "TK", Flag: "🇹🇰"},
	{Name: "Tonga", DialCode: "+676", Code: "TO", Flag: "🇹🇴"},
	{Name: "Trinidad e Tobago", DialCode: "+1868", Code: "TT", Flag: "🇹🇹"},
	{Name: "Tunísia", DialCode: "+216", Code: "TN", Flag: "🇹🇳"},
	{Name: "Turquia", DialCode: "+90", Code: "TR", Flag: "🇹🇷"},
	{Name: "Turcomenistão", DialCode: "+993", Code: "TM", Flag: "🇹🇲"},
	{Name: "Ilhas Turks e Caicos", DialCode: "+1649", Code: "TC", Flag: "🇹🇨"},
	{Name: "Tuvalu", DialCode: "+688", Code: "TV", Flag: "🇹🇻"},
	{Name: "Uganda", DialCode: "+256", Code: "UG", Flag: "🇺🇬"},
	{Name: "Ucrânia", DialCode: "+380", Code: "UA", Flag: "🇺🇦"},
	{Name: "Emirados Árabes Unidos", DialCode: "+971", Code: "AE", Flag: "🇦🇪"},
	{Name: "Grã-Bretanha (Reino Unido, UK)", DialCode: "+44", Code: "GB", Flag: "🇬🇧"},
	{Name: "Estados Unidos", DialCode: "+1", Code: "US", Flag: "🇺🇸"},
	{Name: "Uruguai", DialCode: "+598", Code: "UY", Flag: "🇺🇾"},
	{Name: "Uzbequistão", DialCode: "+998", Code: "UZ", Flag: "🇺🇿"},
	{Name: "Vanuatu", DialCode: "+678", Code: "VU", Flag: "🇻🇺"},
	{Name: "Venezuela", DialCode: "+58", Code: "VE", Flag: "🇻🇪"},
	{Name: "Vietnã", DialCode: "+84", Code: "VN", Flag: "🇻🇳"},
	{Name: "Ilhas Virgens (Inglaterra)", DialCode: "+1284", Code: "VG", Flag: "🇻🇬"},
	{Name: "Ilhas Virgens (Estados Unidos)", DialCode: "+1340", Code: "VI", Flag: "🇻🇮"},
	{Name: "Wallis e Futuna", DialCode: "+681", Code: "WF", Flag: "🇼🇫"},
	{Name: "Iêmen", DialCode: "+967", Code: "YE", Flag: "🇾🇪"},
	{Name: "Zâmbia", DialCode: "+260", Code: "ZM", Flag: "🇿🇲"},
	{Name: "Zimbábue", DialCode: "+263", Code: "ZW", Flag: "🇿🇼"},
	{Name: "Ilhas Aland", DialCode: "+358", Code: "AX", Flag: "🇦🇽"},
}
